version: '2'
services:
  mariadb:
    image: 'mariadb:latest'
    volumes:
      - './mariadb:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  wordpress:
    image: 'wordpress:latest'
    ports:
    - '80:80'
    volumes:
    - './wordpress:/var/www/html'
    depends_on:
    - mariadb
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '8080:80'
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mariadb
  nuxt:
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      HOST: '0.0.0.0'
    command: bash -c "npm install && npm run dev"
    ports:
      - '3000:3000'
